---
# tasks file for docker


- name: Install Docker and Related Packages
  apt: name={{ item }} state=present
  with_items:
          - "{{ pkgs }}"

- name: Make sure docker daemon is running 
  systemd: name=docker state=started

- name: Add user to docker group
  user: name={{ ansible_user }} groups=docker append=yes 

- name: Build Docker image
  docker_image: 
     name: centos-sshd
     pull: no
     path: "{{ role_path }}"
     force: yes
     buildargs:
             dockuser: "{{ dockuser }}"
             pubkey: "{{ pubkey }}"

- name: Create Docker network
  docker_network: name="br01"

- name: Start Docker Container
  docker_container:
          name: "{{ item }}"
          recreate: yes
          image: centos-sshd
          networks:
                  - name: "br01"
  with_items:
          - "{{ groups['sshd_dockers'] }}"
  register: sshd_dockers


- name: Add Docker to Ansible inventory 
  add_host:
          name: "{{ item.ansible_facts.docker_container.Name | regex_replace('.*/','')  }}"
          ansible_host: "{{ item.ansible_facts.docker_container.NetworkSettings.Networks.bridge.IPAddress }}"
          groups: sshd_dockers
  with_items:
        - "{{ sshd_dockers.results  }}"
